# Generated by Django 4.2 on 2026-01-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
