# Generated by Django 4.2 on 2025-12-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('attack_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
